repositories {
    mavenCentral()
    google() // Needed for androidx
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")

    implementation 'org.firstinspires.ftc:Inspection:11.0.0'
    implementation 'org.firstinspires.ftc:Blocks:11.0.0'
    implementation 'org.firstinspires.ftc:RobotCore:11.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.0.0'
    implementation 'org.firstinspires.ftc:Hardware:11.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.0.0'
    implementation 'org.firstinspires.ftc:Vision:11.0.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'redis.clients:jedis:5.2.0'
    implementation 'org.locationtech.jts:jts-core:1.20.0'
}

